version: '3.8'

services:
  pg-db:
    container_name: netflix-content-db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=content-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data3

volumes:
  db:
    driver: local
