server:
  port: 8085

spring:
  application:
    name: content-service
  mvc:
    static-path-pattern: /swagger*

  datasource:
    url: jdbc:postgresql://localhost:5434/content-db
    username: admin
    password: admin

  liquibase:
    change-log: db/changelog-master.yaml
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
